name: Keep Supabase Awake

on:
  schedule:
    - cron: "0 3 * * 0"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping app
        run: |
          python - <<'EOF'
          import urllib.request

          url = "https://cv-wapp.streamlit.app"

          with urllib.request.urlopen(url, timeout=60) as r:
              print("Status:", r.status)
          EOF
